apiVersion: v1
kind: Namespace
metadata:
  name: sailorsdailyjill

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sailorsdailyjill-app
  namespace: sailorsdailyjill
spec:
  selector:
    matchLabels:
      app: sailorsdailyjill-app
  replicas: 3
  template:
    metadata:
      labels:
        app: sailorsdailyjill-app
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: sailorsdailyjill-app
          image: docker.io/thomascross257/sailors-daily-jill:app
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri
                  key: uri
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 0.5
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 250
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 250
            periodSeconds: 60


---
apiVersion: v1
kind: Service
metadata:
  name: sailorsdailyjill-app
  namespace: sailorsdailyjill
spec:
  selector:
    app: sailorsdailyjill-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: LoadBalancer
  loadBalancerIP: 192.168.1.245
  sessionAffinity: ClientIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sailorsdailyjill-nginx
  namespace: sailorsdailyjill
spec:
  selector:
    matchLabels:
      app: sailorsdailyjill-nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: sailorsdailyjill-nginx
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: sailorsdailyjill-nginx
          image: docker.io/thomascross257/sailors-daily-jill:nginx-arm64
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: SERVER_NAME
              value: "sailorsdailyjill.social"
            - name: RESOLVER
              value: "kube-dns.kube-system.svc.cluster.local"
          readinessProbe:
            httpGet:
              path: /
              port: 80
              host: localhost
            initialDelaySeconds: 250
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /
              port: 80
              host: localhost
            initialDelaySeconds: 250
            periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: sailorsdailyjill-nginx
  namespace: sailorsdailyjill
spec:
  selector:
    app: sailorsdailyjill-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: 192.168.1.240
  sessionAffinity: ClientIP
