apiVersion: v1
kind: Namespace
metadata:
  name: sailorsdailyjill

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sailorsdailyjill-app
  namespace: sailorsdailyjill
spec:
  selector:
    matchLabels:
      app: sailorsdailyjill-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sailorsdailyjill-app
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: sailorsdailyjill-app
          image: docker.io/thomascross257/sailorsdailyjill:latest
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-uri
                  key: mongo-uri
          resources:
            limits:
              cpu: 1
              memory: 512Mi
            requests:
              cpu: 0.5  
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 60


---
apiVersion: v1
kind: Service
metadata:
  name: sailorsdailyjill-app
  namespace: sailorsdailyjill
spec:
  selector:
    app: sailorsdailyjill-app
  ports:
    - name: http
      port: 8000
      targetPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sailorsdailyjill-nginx
  namespace: sailorsdailyjill
spec:
  selector:
    matchLabels:
      app: sailorsdailyjill-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: sailorsdailyjill-nginx
    spec:
      containers:
        - name: sailorsdailyjill-nginx
          image: docker.io/thomascross257/sailorsdailyjill:nginx
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/nginx/ssl
          env:
            - name: SERVER_NAME
              value: "sailorsdailyjill.social"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
      volumes:
        - name: ssl-certs
          secret:
            secretName: ssl-certs
            optional: false


---
apiVersion: v1
kind: Service
metadata:
  name: sailorsdailyjill-nginx
  namespace: sailorsdailyjill
spec:
  selector:
    app: sailorsdailyjill-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
  type: LoadBalancer